CREATE TABLE "YAGO"."FACTS"
  (
    "ID"       NUMBER(*,0),
    "RELATION" VARCHAR2(255 BYTE),
    "ARG1"     VARCHAR2(255 BYTE),
    "ARG2"     VARCHAR2(512 BYTE),
    "CONFIDENCE" FLOAT(126)
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."FACTS_A1_A2_REL_C_IDX" ON "YAGO"."FACTS"
  (
    "ARG1",
    "ARG2",
    "RELATION",
    "CONFIDENCE"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."FACTS_A1_REL_A2_C_IDX" ON "YAGO"."FACTS"
  (
    "ARG1",
    "RELATION",
    "ARG2",
    "CONFIDENCE"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."FACTS_A2_REL_A1_C_IDX" ON "YAGO"."FACTS"
  (
    "ARG2",
    "RELATION",
    "ARG1",
    "CONFIDENCE"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."FACTS_REL_A1_A2_C_IDX" ON "YAGO"."FACTS"
  (
    "RELATION",
    "ARG1",
    "ARG2",
    "CONFIDENCE"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE TABLE "YAGO"."GAZETTEER"
  (
    "UFI"          NUMBER(15,5),
    "LAT"          NUMBER(15,5),
    "LON"          NUMBER(15,5),
    "FULL_NAME"    VARCHAR2(150 BYTE),
    "SDO_GEOMETRY" "MDSYS"."SDO_GEOMETRY"
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."GAZ_LAT_LON_ID" ON "YAGO"."GAZETTEER"
  (
    "LAT",
    "LON",
    "UFI"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."GAZ_LON_LAT_ID" ON "YAGO"."GAZETTEER"
  (
    "LON",
    "LAT",
    "UFI"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."GAZ_UFI_LAT_LON" ON "YAGO"."GAZETTEER"
  (
    "UFI",
    "LAT",
    "LON"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."GAZ_FULL_NAME_LAT_LON" ON "YAGO"."GAZETTEER"
  (
    "FULL_NAME",
    "LAT",
    "LON"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
  CREATE INDEX "YAGO"."GAZ_LAT_LON_FULL_NAME_ID" ON "YAGO"."GAZETTEER"
  (
    "LAT",
    "LON",
    "FULL_NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;
CREATE INDEX "YAGO"."GAZ_LON_LAT_FULL_NAME_ID" ON "YAGO"."GAZETTEER"
  (
    "LON",
    "LAT",
    "FULL_NAME"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;